setwd("C:/Users/Edwin/Documents/R/UCI HAR Dataset/train")
x_train <- read.table("X_train.txt", header = FALSE)
setwd("C:/Users/Edwin/Documents/R/UCI HAR Dataset/test")
x_test <- read.table("X_test.txt", header = FALSE)
library(plyr);library(dplyr);library(Hmisc);library(stringr)
train <- mutate(x_train, dClass="Train")
test <- mutate(x_test, dClass="Test")
alldata <- rbind.data.frame(test,train)
setwd("C:/Users/Edwin/Documents/R/UCI HAR Dataset")
cols <- readLines("features.txt")
##cols1 <- strsplit(cols,"\\ ")
##second_element <- function(x){x[2]}
##cols2 <- sapply(cols1, second_element)
cols3 <- c(cols,"test_train")
cols4 <- gsub(" ","",cols3)
cols5 <- gsub("-","_",cols4)
cols6 <- tolower(cols5)
cols7 <- str_replace_all(cols6, "([()])", "")
cols8 <- str_replace_all(cols7, "([,])", "_")
#cols6 <- gsub(")","",cols5)
#cols7 <- gsub("(","",cols6)
colnames(alldata) <- cols8
alldata[, 'test_train'] <- as.factor(alldata[, 'test_train'])
allstd <- select(alldata, contains("std"))
allmeans <- select(alldata, contains("mean"))
Tidy2nd <- alldata %>% group_by(test_train) %>% summarise_each(funs(mean))
